 Ficha Técnica: Dataset Credit Approval (CRX)
Descripción General
Este dataset, proveniente del repositorio UCI Machine Learning, contiene solicitudes de tarjetas de crédito reales. Debido a la sensibilidad de la información bancaria, todos los nombres de las variables y sus valores originales fueron anonimizados y sustituidos por símbolos (A1, A2, etc.).

Es un dataset "sucio" en su origen, con una mezcla de datos categóricos (letras) y continuos (números), además de valores faltantes (identificados inicialmente como ?).

Columna,Tipo de Dato,Significado Probable
A1,Categórico,"Género / Estado Civil (a, b)"
A2,Continuo,Edad del solicitante
A3,Continuo,Deuda actual / Ratio de deuda
A4,Categórico,"Estado del cliente (Casado, Soltero, etc.)"
A5,Categórico,"Sector de empleo (Educación, Salud, etc.)"
A6,Categórico,Etnia / Nacionalidad
A7,Continuo,Años de experiencia laboral
A8,Categórico,¿Tiene deudas previas? (t/f)
A9,Categórico,¿Está empleado actualmente? (t/f)
A10,Continuo,Score crediticio / Número de cuentas
A11,Categórico,¿Tiene licencia de conducir / ID? (t/f)
A12,Categórico,Tipo de ciudadanía
A13,Continuo,Salario / Ingresos mensuales
A14,ELIMINADO,Código Postal (Zip Code)
A15,Continuo,Saldo en cuenta / Otros ingresos
Target,Binario,Veredicto: 1 (Aprobado) / 0 (Denegado)

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display

ruta_crx = '/Users/mac/Desktop/datasets/credit aproval/credit+approval/crx.data'

nombres_cols = [f'A{i}' for i in range(1, 16)] + ['Target']

df_crudo = pd.read_csv(ruta_crx, header=None, names=nombres_cols, na_values='?')

print(f" Dataset 'CRX' cargado. Filas: {df_crudo.shape[0]}, Columnas: {df_crudo.shape[1]}")
display(df_crudo.head(10))

:

In [ ]:
df_limpio = df_crudo.copy()

df_limpio = df_limpio.drop(columns=['A14'])
print(" Columna A14 eliminada por ser considerada ruido geográfico.")

cols_num = df_limpio.select_dtypes(include=[np.number]).columns.tolist()
cols_cat = df_limpio.select_dtypes(include=['object']).columns.tolist()
cols_cat.remove('Target')

for col in cols_num:
    df_limpio[col] = df_limpio[col].fillna(df_limpio[col].mean())
for col in cols_cat:
    df_limpio[col] = df_limpio[col].fillna(df_limpio[col].mode()[0])

for col in cols_cat:
    df_limpio[col], _ = pd.factorize(df_limpio[col])

df_limpio['Target'] = df_limpio['Target'].map({'+': 1, '-': 0})

print(" Limpieza e Imputación completada.")
display(df_limpio.head(5))

 Columna A14 eliminada por ser considerada ruido geográfico.
 Limpieza e Imputación completada.

/var/folders/pd/cm5pc6bx0092jjcvgn8m3rwh0000gn/T/ipykernel_30380/2892190597.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols_cat = df_limpio.select_dtypes(include=['object']).columns.tolist()

   A1     A2     A3  A4  A5  A6  A7    A8  A9  A10  A11  A12  A13  A15  Target
0   0  30.83  0.000   0   0   0   0  1.25   0    0    1    0    0    0       1
1   1  58.67  4.460   0   0   1   1  3.04   0    0    6    0    0  560       1
2   1  24.50  0.500   0   0   1   1  1.50   0    1    0    0    0  824       1
3   0  27.83  1.540   0   0   0   0  3.75   0    0    5    1    0    3       1
4   0  20.17  5.625   0   0   0   0  1.71   0    1    0    0    1    0       1

In [ ]:

X = df_limpio.drop(columns=['Target'])

y = df_limpio['Target']

print("🏗️ Separación de matrices finalizada.")
print(f"Dimensiones de X: {X.shape}")
print(f"Dimensiones de y: {y.shape}")

🏗️ Separación de matrices finalizada.
Dimensiones de X: (690, 14)
Dimensiones de y: (690,)

In [ ]:
print(" MATRIZ X (Características del Cliente - Sin A14):")
from IPython.display import display
display(X.head(5))

print("\n" + "="*60 + "\n")

print(" VECTOR y (Decisión del Crédito: 0=No, 1=Sí):")
display(y.head(5))

print("-" * 60)
print(f"Variables en X: {list(X.columns)}")
print("Estado: LISTO PARA NORMALIZACIÓN (FASE 3)")

 MATRIZ X (Características del Cliente - Sin A14):

   A1     A2     A3  A4  A5  A6  A7    A8  A9  A10  A11  A12  A13  A15
0   0  30.83  0.000   0   0   0   0  1.25   0    0    1    0    0    0
1   1  58.67  4.460   0   0   1   1  3.04   0    0    6    0    0  560
2   1  24.50  0.500   0   0   1   1  1.50   0    1    0    0    0  824
3   0  27.83  1.540   0   0   0   0  3.75   0    0    5    1    0    3
4   0  20.17  5.625   0   0   0   0  1.71   0    1    0    0    1    0

============================================================

 VECTOR y (Decisión del Crédito: 0=No, 1=Sí):

0    1
1    1
2    1
3    1
4    1
Name: Target, dtype: int64

------------------------------------------------------------
Variables en X: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A15']
Estado: LISTO PARA NORMALIZACIÓN (FASE 3)